#! /bin/bash

BUSYBOX="/bin/busybox"
DIR="/usr/share/mkiniramfs-ll/usr/lib/"

function debug() {
    echo "Echec with $1"
    exit $2
}

function copyInDir() {
    echo "copy $1 into $DIR"
    cp $1 $DIR || debug $1 1
    echo "All files has been copyed"
}

function fileOrDir() {
    if [ -f $1 ] ; then
        copyInDir "$1"
    elif [ -f /lib64/$1 ] ; then
        copyInDir "/lib64/$1"
    else
        echo "file $1 not found anywhere"
    fi
}

if [ -f "${BUSYBOX}" ] ; then
    echo "copy file required by $BUSYBOX"
    v_lib="$(ldd $BUSYBOX | awk '{print $1}')"
   
    for i in $v_lib ; do
        fileOrDir $i
    done
else
    echo "$BUSYBOX not found"
fi
