#! /bin/bash

WORKDIR="$1"
D_PROC="$WORKDIR/proc"
D_SYS="$WORKDIR/sys"
D_DEV="$WORKDIR/dev"

function ifAllDir() {
    if [ -d $D_PROC ] && [ -d $D_SYS ] && [ -d $D_DEV ]; then
        return 0;
    else
        return 1;
    fi
}

function ifAlrealyMount() {
    local p_proc="$D_PROC/tty"
    local p_sys="$D_SYS/dev"
    local p_dev="$D_DEV/disk"
    
    if [ -d $p_proc ] && [ -d $p_sys ] && [ -d $p_dev ] ; then
        return 0
    else
        return 1
    fi
}

if ifAllDir ; then

    echo "The Begin..."

    if ifAlrealyMount ; then
        echo "filesystem alrealy mount..."
    else
        mount -t proc proc $D_PROC || exit 1
        mount --rbind /sys $D_SYS ||  exit 1
        mount --rbind /dev $D_DEV || exit 1
        mount --make-rslave $D_SYS || exit 1
        mount --make-rslave $D_DEV || exit 1
        echo "Mount complete, it's ready for chroot..."
    fi
else
    echo "Directory not exist..."
    exit 1
fi

function ifGentooHere() {
    local d_src="$WORKDIR/usr/src"
    local d_boot="$WORKDIR/boot/grub"
    local d_var="$WORKDIR/var/log"
    local d_etc="$WORKDIR/etc/portage"

    if [ -d $d_src ] && [ -d $d_boot ] && [ -d $d_var ] && [ -d $d_etc ]; then
        return 0
    else
        echo "You must download a stage 3 for gentoo and unpack it."
        return 1
    fi
}

if ifGentooHere ; then
    chroot $WORKDIR /bin/bash || exit 1
else
    echo "The End."
    exit 1
fi
