#! /bin/sh

WORDIR=$1

if [[ -d $1 ]]; then
    # Remove all character '/' from $1
    local i="${WORKDIR%%[/]*}"

    mount -t proc proc $i/proc || echo "fail to mount proc" && exit 1
    mount --rbind /sys $i/sys || echo "fail to mount sys" && exit 1
    mount --rbind /dev $i/dev || echo "fail to mount dev" && exit 1
    mount --make-rslave $i/sys || echo "fail to make slave sys" && exit 1
    mount --make-rslave $i/dev || echo "fail to make slave dev" && exit 1

else
    echo "$1 not valid, argument must be a directory..." && exit 1
fi

chroot $1/ /bin/bash || echo "fail to chroot..." && exit 1
